### ISSUE TITLE
Use any-promise for promise support

### ISSUE THREAD

**Issue by RangerMauve** [zxdong262/promise-mongo#1]
[Any-promise](https://www.npmjs.com/package/any-promise) automatically uses whatever promise libraries are installed (or the native implementation if one exists) so it makes things easier to integrate with projects.

**Comment by zxdong262** [comment]
https://github.com/zxdong262/promise-mongo/commit/abbf270a03ccda87e880f965722c4efe393ef128

0.2.0 include promise module for non-es6 user.
