### ISSUE TITLE
loved the project

### ISSUE THREAD

**Issue by tony1223** [zxdong262/promise-mongo#2]
There's no issues so far,just want to say that's it really a good and useful project for me. ;)
Good job.

but if possible, could we made some promise helper for cf.limit,cf.sort? 

I wrote something like this:

var cf=pm.cf;
var sort = function(option){
  return function(c){ 
    return cf.sort(c,option); 
  };
}

var limit = function(option){
  return function(c){
    return cf.limit(c,option); 
  }; 
}

then I could do something like this:
return db.urls.find(null,{url: 1,createDate:1})
    .then(limit(100))
    .then(sort({createDate:-1}));

**Comment by zxdong262** [comment]
You are right, this is better. I will rewrite this part, maybe add some new methods.
